/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author njama
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    //initialises the home frame to start the app
     public Home(String user){
        initComponents();
        lblUser.setText(user);
        btnLogin.setVisible(false);
        btnProfile.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        btnCart = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        jLabel68 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlHammer1 = new javax.swing.JPanel();
        lblHammer1_pic = new javax.swing.JLabel();
        lblHammer1_name = new javax.swing.JLabel();
        lblHammer1_price = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlDrill1 = new javax.swing.JPanel();
        lblDrill1_pic = new javax.swing.JLabel();
        lblDrill1_name = new javax.swing.JLabel();
        lblDrill1_price = new javax.swing.JLabel();
        pnlHammer3 = new javax.swing.JPanel();
        lblHammer3_pic = new javax.swing.JLabel();
        lblHammer3_name = new javax.swing.JLabel();
        lblHammer3_price = new javax.swing.JLabel();
        pnlHammer2 = new javax.swing.JPanel();
        lblHammer2_pic = new javax.swing.JLabel();
        lblHammer2_name = new javax.swing.JLabel();
        lblHammer2_price = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnlDrill3 = new javax.swing.JPanel();
        lblDrill3_pic = new javax.swing.JLabel();
        lblDrill3_name = new javax.swing.JLabel();
        lblDrill3_price = new javax.swing.JLabel();
        pnlDrill2 = new javax.swing.JPanel();
        lblDrill2_pic = new javax.swing.JLabel();
        lblDrill2_name = new javax.swing.JLabel();
        lblDrill2_price = new javax.swing.JLabel();
        pnlScrewDriver1 = new javax.swing.JPanel();
        lblScrew1_pic = new javax.swing.JLabel();
        lblScrew1_name = new javax.swing.JLabel();
        lblScrew1_price = new javax.swing.JLabel();
        pnlScrewDriver2 = new javax.swing.JPanel();
        lblScrew2_pic = new javax.swing.JLabel();
        lblScrew2_name = new javax.swing.JLabel();
        lblScrew2_price = new javax.swing.JLabel();
        pnlScrewDriver3 = new javax.swing.JPanel();
        lblScrew3_pic = new javax.swing.JLabel();
        lblScrew3_name = new javax.swing.JLabel();
        lblScrew3_price = new javax.swing.JLabel();
        pnlSpanner1 = new javax.swing.JPanel();
        lblSpanner1_pic = new javax.swing.JLabel();
        lblSpanner1_name = new javax.swing.JLabel();
        lblSpanner1_price = new javax.swing.JLabel();
        pnlSpanner2 = new javax.swing.JPanel();
        lblSpanner2_pic = new javax.swing.JLabel();
        lblSpanner2_name = new javax.swing.JLabel();
        lblSpanner2_price = new javax.swing.JLabel();
        pnlSpanner3 = new javax.swing.JPanel();
        lblSpanner3_pic = new javax.swing.JLabel();
        lblSpanner3_name = new javax.swing.JLabel();
        lblSpanner3_price = new javax.swing.JLabel();
        pnlPliers1 = new javax.swing.JPanel();
        lblPliers1_pic = new javax.swing.JLabel();
        lblPliers1_name = new javax.swing.JLabel();
        lblPliers1_price = new javax.swing.JLabel();
        pnlPliers2 = new javax.swing.JPanel();
        lblPliers2_pic = new javax.swing.JLabel();
        lblPliers2_name = new javax.swing.JLabel();
        lblPliers2_price = new javax.swing.JLabel();
        pnlPliers3 = new javax.swing.JPanel();
        lblPliers3_pic = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        lblPliers3_name = new javax.swing.JLabel();
        lblPliers3_price = new javax.swing.JLabel();
        pnlBaN1 = new javax.swing.JPanel();
        lblBaN_pic = new javax.swing.JLabel();
        lblBaN_name = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        pnlBaN2 = new javax.swing.JPanel();
        lblBaN2_pic = new javax.swing.JLabel();
        lblBaN2_name = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        pnlBaN3 = new javax.swing.JPanel();
        lblBaN3_pic = new javax.swing.JLabel();
        lblBaN3_name = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel35.setText("R60.00");

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(870, 610));
        getContentPane().setLayout(null);

        btnCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopping-cart_40x40.png"))); // NOI18N
        btnCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartActionPerformed(evt);
            }
        });
        getContentPane().add(btnCart);
        btnCart.setBounds(780, 20, 50, 40);

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(690, 20, 80, 40);

        btnProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_40x40.png"))); // NOI18N
        getContentPane().add(btnProfile);
        btnProfile.setBounds(630, 20, 50, 40);

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"))); // NOI18N
        jLabel68.setToolTipText("");
        getContentPane().add(jLabel68);
        jLabel68.setBounds(10, 10, 110, 70);

        lblUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUser.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lblUser);
        lblUser.setBounds(630, 20, 140, 40);

        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("What are you looking for?");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(120, 30, 500, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2023-09-05 131147.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(5000, 5000));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 974, 90);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Hammers");

        pnlHammer1.setBackground(new java.awt.Color(255, 153, 51));
        pnlHammer1.setPreferredSize(new java.awt.Dimension(235, 300));
        pnlHammer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHammer1MouseClicked(evt);
            }
        });

        lblHammer1_pic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHammer1_pic.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jarret\\Documents\\NetBeansProjects\\BuiltDifferent2.0\\src\\stanley_ball_pein_hammer_340g_179x180.jpg")); // NOI18N
        lblHammer1_pic.setName("stanley_ball_pein_hammer_340g_179x180.jpg"); // NOI18N
        lblHammer1_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHammer1_picMouseClicked(evt);
            }
        });

        lblHammer1_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHammer1_name.setText("Stanley Ball Pein Hammer 340g");

        lblHammer1_price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHammer1_price.setText("R185.00");

        javax.swing.GroupLayout pnlHammer1Layout = new javax.swing.GroupLayout(pnlHammer1);
        pnlHammer1.setLayout(pnlHammer1Layout);
        pnlHammer1Layout.setHorizontalGroup(
            pnlHammer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHammer1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlHammer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHammer1_name)
                    .addComponent(lblHammer1_price)
                    .addComponent(lblHammer1_pic))
                .addGap(26, 26, 26))
        );
        pnlHammer1Layout.setVerticalGroup(
            pnlHammer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHammer1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblHammer1_pic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHammer1_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHammer1_price)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Drills");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Screwdrivers");

        pnlDrill1.setBackground(new java.awt.Color(255, 153, 51));
        pnlDrill1.setPreferredSize(new java.awt.Dimension(244, 288));

        lblDrill1_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dewalt_brushless_hammer_drill_R4150_179x180.jpg"))); // NOI18N
        lblDrill1_pic.setName("Dewalt_brushless_hammer_drill_R4150_179x180.jpg"); // NOI18N
        lblDrill1_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDrill1_picMouseClicked(evt);
            }
        });

        lblDrill1_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDrill1_name.setText("DeWalt Hammer Drill");

        lblDrill1_price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDrill1_price.setText("R4150.00");

        javax.swing.GroupLayout pnlDrill1Layout = new javax.swing.GroupLayout(pnlDrill1);
        pnlDrill1.setLayout(pnlDrill1Layout);
        pnlDrill1Layout.setHorizontalGroup(
            pnlDrill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDrill1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlDrill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDrill1_pic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDrill1_price)
                    .addComponent(lblDrill1_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlDrill1Layout.setVerticalGroup(
            pnlDrill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDrill1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblDrill1_pic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDrill1_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDrill1_price)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlHammer3.setBackground(new java.awt.Color(255, 153, 51));
        pnlHammer3.setPreferredSize(new java.awt.Dimension(235, 300));

        lblHammer3_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot_2023-09-05_161147_179x180.png"))); // NOI18N
        lblHammer3_pic.setName("Screenshot_2023-09-05_161147_179x180.png"); // NOI18N
        lblHammer3_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHammer3_picMouseClicked(evt);
            }
        });

        lblHammer3_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHammer3_name.setText("Grip Brick Chisel Hammer");

        lblHammer3_price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHammer3_price.setText("R439.99");

        javax.swing.GroupLayout pnlHammer3Layout = new javax.swing.GroupLayout(pnlHammer3);
        pnlHammer3.setLayout(pnlHammer3Layout);
        pnlHammer3Layout.setHorizontalGroup(
            pnlHammer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHammer3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlHammer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHammer3_price)
                    .addComponent(lblHammer3_name))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHammer3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblHammer3_pic)
                .addGap(23, 23, 23))
        );
        pnlHammer3Layout.setVerticalGroup(
            pnlHammer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHammer3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblHammer3_pic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHammer3_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHammer3_price)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlHammer2.setBackground(new java.awt.Color(255, 153, 51));
        pnlHammer2.setPreferredSize(new java.awt.Dimension(235, 300));

        lblHammer2_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/milwaukee_hammer_R599_179x180.jpg"))); // NOI18N
        lblHammer2_pic.setName("milwaukee_hammer_R599_179x180.jpg"); // NOI18N
        lblHammer2_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHammer2_picMouseClicked(evt);
            }
        });

        lblHammer2_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHammer2_name.setText("Milwaukee Clawed Hammer");

        lblHammer2_price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHammer2_price.setText("R599.00");

        javax.swing.GroupLayout pnlHammer2Layout = new javax.swing.GroupLayout(pnlHammer2);
        pnlHammer2.setLayout(pnlHammer2Layout);
        pnlHammer2Layout.setHorizontalGroup(
            pnlHammer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHammer2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(pnlHammer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHammer2_pic)
                    .addComponent(lblHammer2_name)
                    .addComponent(lblHammer2_price))
                .addGap(26, 26, 26))
        );
        pnlHammer2Layout.setVerticalGroup(
            pnlHammer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHammer2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblHammer2_pic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHammer2_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHammer2_price)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Measuring Tools");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Pliers");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Spanners");

        pnlDrill3.setBackground(new java.awt.Color(255, 153, 51));
        pnlDrill3.setPreferredSize(new java.awt.Dimension(244, 288));

        lblDrill3_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CAT_Rotary-Hammer_1500W_R3495.00_1_179x180.png"))); // NOI18N
        lblDrill3_pic.setName("CAT_Rotary-Hammer_1500W_R3495.00_1_179x180.png"); // NOI18N
        lblDrill3_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDrill3_picMouseClicked(evt);
            }
        });

        lblDrill3_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDrill3_name.setText("CAT Rotary Hammer 1500W");

        lblDrill3_price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDrill3_price.setText("R3,495.00");
        lblDrill3_price.setToolTipText("");

        javax.swing.GroupLayout pnlDrill3Layout = new javax.swing.GroupLayout(pnlDrill3);
        pnlDrill3.setLayout(pnlDrill3Layout);
        pnlDrill3Layout.setHorizontalGroup(
            pnlDrill3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDrill3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlDrill3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDrill3_pic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDrill3_price, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrill3_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlDrill3Layout.setVerticalGroup(
            pnlDrill3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDrill3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblDrill3_pic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDrill3_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDrill3_price)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnlDrill2.setBackground(new java.awt.Color(255, 153, 51));
        pnlDrill2.setPreferredSize(new java.awt.Dimension(244, 288));

        lblDrill2_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makita_impact_drill_710W_R1699.99_179x180.jpg"))); // NOI18N
        lblDrill2_pic.setName("Makita_impact_drill_710W_R1699.99_179x180.jpg"); // NOI18N
        lblDrill2_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDrill2_picMouseClicked(evt);
            }
        });

        lblDrill2_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDrill2_name.setText("Makita Impact Drill 710W");

        lblDrill2_price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDrill2_price.setText("R1,699.99");

        javax.swing.GroupLayout pnlDrill2Layout = new javax.swing.GroupLayout(pnlDrill2);
        pnlDrill2.setLayout(pnlDrill2Layout);
        pnlDrill2Layout.setHorizontalGroup(
            pnlDrill2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDrill2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlDrill2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDrill2_pic)
                    .addComponent(lblDrill2_name)
                    .addComponent(lblDrill2_price))
                .addGap(26, 26, 26))
        );
        pnlDrill2Layout.setVerticalGroup(
            pnlDrill2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDrill2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblDrill2_pic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDrill2_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDrill2_price)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlScrewDriver1.setBackground(new java.awt.Color(255, 153, 51));
        pnlScrewDriver1.setPreferredSize(new java.awt.Dimension(244, 288));

        lblScrew1_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stahlwille_7pc_screwdriver_set_R1990.00_1_179x180.jpg"))); // NOI18N
        lblScrew1_pic.setName("Stahlwille_7pc_screwdriver_set_R1990.00_1_179x180.jpg"); // NOI18N
        lblScrew1_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblScrew1_picMouseClicked(evt);
            }
        });

        lblScrew1_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblScrew1_name.setText("Stahlwille 7pc Screwdriver Set");

        lblScrew1_price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblScrew1_price.setText("R680.00");

        javax.swing.GroupLayout pnlScrewDriver1Layout = new javax.swing.GroupLayout(pnlScrewDriver1);
        pnlScrewDriver1.setLayout(pnlScrewDriver1Layout);
        pnlScrewDriver1Layout.setHorizontalGroup(
            pnlScrewDriver1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScrewDriver1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlScrewDriver1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblScrew1_name, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblScrew1_pic)
                    .addComponent(lblScrew1_price))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlScrewDriver1Layout.setVerticalGroup(
            pnlScrewDriver1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScrewDriver1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblScrew1_pic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblScrew1_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblScrew1_price)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlScrewDriver2.setBackground(new java.awt.Color(255, 153, 51));
        pnlScrewDriver2.setPreferredSize(new java.awt.Dimension(244, 288));

        lblScrew2_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stanley_stubby_multibit_screwdriver_R679.99_179x180.jpg"))); // NOI18N
        lblScrew2_pic.setName("Stanley_stubby_multibit_screwdriver_R679.99_179x180.jpg"); // NOI18N
        lblScrew2_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblScrew2_picMouseClicked(evt);
            }
        });

        lblScrew2_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblScrew2_name.setText("Stanley Multibit Screwdriver");

        lblScrew2_price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblScrew2_price.setText("R599.90");

        javax.swing.GroupLayout pnlScrewDriver2Layout = new javax.swing.GroupLayout(pnlScrewDriver2);
        pnlScrewDriver2.setLayout(pnlScrewDriver2Layout);
        pnlScrewDriver2Layout.setHorizontalGroup(
            pnlScrewDriver2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScrewDriver2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlScrewDriver2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblScrew2_name)
                    .addComponent(lblScrew2_pic)
                    .addComponent(lblScrew2_price))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlScrewDriver2Layout.setVerticalGroup(
            pnlScrewDriver2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScrewDriver2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblScrew2_pic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblScrew2_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblScrew2_price)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlScrewDriver3.setBackground(new java.awt.Color(255, 153, 51));
        pnlScrewDriver3.setPreferredSize(new java.awt.Dimension(244, 288));

        lblScrew3_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/milwaukee_8pc_screwdriver_set_R630_179x180.jpg"))); // NOI18N
        lblScrew3_pic.setName("Milwaukee_8pc_screwdriver_set_R630_179x180.jpg"); // NOI18N
        lblScrew3_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblScrew3_picMouseClicked(evt);
            }
        });

        lblScrew3_name.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblScrew3_name.setText("Milwaukee 8pc Screwdriver Set");

        lblScrew3_price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblScrew3_price.setText("R709.99");

        javax.swing.GroupLayout pnlScrewDriver3Layout = new javax.swing.GroupLayout(pnlScrewDriver3);
        pnlScrewDriver3.setLayout(pnlScrewDriver3Layout);
        pnlScrewDriver3Layout.setHorizontalGroup(
            pnlScrewDriver3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScrewDriver3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlScrewDriver3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblScrew3_name)
                    .addGroup(pnlScrewDriver3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlScrewDriver3Layout.createSequentialGroup()
                            .addComponent(lblScrew3_pic)
                            .addGap(21, 21, 21))
                        .addGroup(pnlScrewDriver3Layout.createSequentialGroup()
                            .addComponent(lblScrew3_price)
                            .addContainerGap()))))
        );
        pnlScrewDriver3Layout.setVerticalGroup(
            pnlScrewDriver3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScrewDriver3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblScrew3_pic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblScrew3_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblScrew3_price)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnlSpanner1.setBackground(new java.awt.Color(255, 153, 51));
        pnlSpanner1.setPreferredSize(new java.awt.Dimension(244, 288));

        lblSpanner1_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STAHLWILLE_COMBI_SPANNERS_R260_179x180.jpg"))); // NOI18N
        lblSpanner1_pic.setName("STAHLWILLE_COMBI_SPANNERS_R260_179x180.jpg"); // NOI18N
        lblSpanner1_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSpanner1_picMouseClicked(evt);
            }
        });

        lblSpanner1_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSpanner1_name.setText("Stahwille Combi Spanner");

        lblSpanner1_price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSpanner1_price.setText("R260.00");

        javax.swing.GroupLayout pnlSpanner1Layout = new javax.swing.GroupLayout(pnlSpanner1);
        pnlSpanner1.setLayout(pnlSpanner1Layout);
        pnlSpanner1Layout.setHorizontalGroup(
            pnlSpanner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSpanner1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlSpanner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSpanner1_pic)
                    .addComponent(lblSpanner1_name)
                    .addComponent(lblSpanner1_price))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlSpanner1Layout.setVerticalGroup(
            pnlSpanner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSpanner1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblSpanner1_pic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSpanner1_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSpanner1_price)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlSpanner2.setBackground(new java.awt.Color(255, 153, 51));
        pnlSpanner2.setPreferredSize(new java.awt.Dimension(244, 288));

        lblSpanner2_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stanley_ratchet_spanner_R150_179x180.jpg"))); // NOI18N
        lblSpanner2_pic.setName("Stanley_ratchet_spanner_R150_179x180.jpg"); // NOI18N
        lblSpanner2_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSpanner2_picMouseClicked(evt);
            }
        });

        lblSpanner2_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSpanner2_name.setText("Stanley Ratchet Spanner");

        lblSpanner2_price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSpanner2_price.setText("R250.00");

        javax.swing.GroupLayout pnlSpanner2Layout = new javax.swing.GroupLayout(pnlSpanner2);
        pnlSpanner2.setLayout(pnlSpanner2Layout);
        pnlSpanner2Layout.setHorizontalGroup(
            pnlSpanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSpanner2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlSpanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSpanner2_pic)
                    .addComponent(lblSpanner2_name)
                    .addComponent(lblSpanner2_price))
                .addGap(25, 25, 25))
        );
        pnlSpanner2Layout.setVerticalGroup(
            pnlSpanner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSpanner2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblSpanner2_pic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSpanner2_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSpanner2_price)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlSpanner3.setBackground(new java.awt.Color(255, 153, 51));
        pnlSpanner3.setPreferredSize(new java.awt.Dimension(244, 288));

        lblSpanner3_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stahlwille_Tube_Spanner_Sets_R2080_179x180.jpg"))); // NOI18N
        lblSpanner3_pic.setName("Stahlwille_Tube_Spanner_Sets_R2080_179x180.jpg"); // NOI18N
        lblSpanner3_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSpanner3_picMouseClicked(evt);
            }
        });

        lblSpanner3_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSpanner3_name.setText("Stahlwille Tube Spanner Set");

        lblSpanner3_price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSpanner3_price.setText("R2,080.00");

        javax.swing.GroupLayout pnlSpanner3Layout = new javax.swing.GroupLayout(pnlSpanner3);
        pnlSpanner3.setLayout(pnlSpanner3Layout);
        pnlSpanner3Layout.setHorizontalGroup(
            pnlSpanner3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSpanner3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlSpanner3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSpanner3_pic)
                    .addComponent(lblSpanner3_name)
                    .addComponent(lblSpanner3_price))
                .addGap(23, 23, 23))
        );
        pnlSpanner3Layout.setVerticalGroup(
            pnlSpanner3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSpanner3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblSpanner3_pic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSpanner3_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSpanner3_price)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlPliers1.setBackground(new java.awt.Color(255, 153, 51));
        pnlPliers1.setPreferredSize(new java.awt.Dimension(244, 288));

        lblPliers1_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/king_tony_long_nose_pliers_R290_179x180.jpg"))); // NOI18N
        lblPliers1_pic.setName("King_tony_long_nose_pliers_R290_179x180.jpg"); // NOI18N
        lblPliers1_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPliers1_picMouseClicked(evt);
            }
        });

        lblPliers1_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPliers1_name.setText("King Tony Long Nose Pliers");

        lblPliers1_price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPliers1_price.setText("R290.00");

        javax.swing.GroupLayout pnlPliers1Layout = new javax.swing.GroupLayout(pnlPliers1);
        pnlPliers1.setLayout(pnlPliers1Layout);
        pnlPliers1Layout.setHorizontalGroup(
            pnlPliers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPliers1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlPliers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPliers1_pic)
                    .addComponent(lblPliers1_name)
                    .addComponent(lblPliers1_price))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlPliers1Layout.setVerticalGroup(
            pnlPliers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPliers1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblPliers1_pic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPliers1_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPliers1_price)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlPliers2.setBackground(new java.awt.Color(255, 153, 51));
        pnlPliers2.setPreferredSize(new java.awt.Dimension(244, 288));

        lblPliers2_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stanley_Mini_side_cutters_100_R110_179x180.jpg"))); // NOI18N
        lblPliers2_pic.setName("Stanley_Mini_side_cutters_100_R110_179x180.jpg"); // NOI18N
        lblPliers2_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPliers2_picMouseClicked(evt);
            }
        });

        lblPliers2_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPliers2_name.setText("Stanley Mini Side Cutters");

        lblPliers2_price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPliers2_price.setText("R110.00");

        javax.swing.GroupLayout pnlPliers2Layout = new javax.swing.GroupLayout(pnlPliers2);
        pnlPliers2.setLayout(pnlPliers2Layout);
        pnlPliers2Layout.setHorizontalGroup(
            pnlPliers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPliers2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlPliers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPliers2_pic)
                    .addComponent(lblPliers2_name)
                    .addComponent(lblPliers2_price))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlPliers2Layout.setVerticalGroup(
            pnlPliers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPliers2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblPliers2_pic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPliers2_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPliers2_price)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlPliers3.setBackground(new java.awt.Color(255, 153, 51));
        pnlPliers3.setPreferredSize(new java.awt.Dimension(244, 288));

        lblPliers3_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ridgid_water_pump_pliers_R695_1_179x180.jpg"))); // NOI18N
        lblPliers3_pic.setName("Ridgid_water_pump_pliers_R695_1_179x180.jpg"); // NOI18N
        lblPliers3_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPliers3_picMouseClicked(evt);
            }
        });

        lblPliers3_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPliers3_name.setText("Ridgid Water Pump Pliers ");

        lblPliers3_price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPliers3_price.setText("R695");

        javax.swing.GroupLayout pnlPliers3Layout = new javax.swing.GroupLayout(pnlPliers3);
        pnlPliers3.setLayout(pnlPliers3Layout);
        pnlPliers3Layout.setHorizontalGroup(
            pnlPliers3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPliers3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlPliers3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPliers3_pic)
                    .addGroup(pnlPliers3Layout.createSequentialGroup()
                        .addComponent(lblPliers3_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPliers3_price))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPliers3Layout.setVerticalGroup(
            pnlPliers3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPliers3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblPliers3_pic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPliers3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel58)
                    .addGroup(pnlPliers3Layout.createSequentialGroup()
                        .addComponent(lblPliers3_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPliers3_price)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlBaN1.setBackground(new java.awt.Color(255, 153, 51));
        pnlBaN1.setPreferredSize(new java.awt.Dimension(244, 288));

        lblBaN_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot_2023-09-05_164900_179x180m1.png"))); // NOI18N
        lblBaN_pic.setName("Screenshot_2023-09-05_164900_179x180m1.png"); // NOI18N
        lblBaN_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBaN_picMouseClicked(evt);
            }
        });

        lblBaN_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBaN_name.setText("Stanley 0-34-108Tape Measure");

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel61.setText("R429.00");

        javax.swing.GroupLayout pnlBaN1Layout = new javax.swing.GroupLayout(pnlBaN1);
        pnlBaN1.setLayout(pnlBaN1Layout);
        pnlBaN1Layout.setHorizontalGroup(
            pnlBaN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaN1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlBaN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBaN_name)
                    .addComponent(lblBaN_pic)
                    .addComponent(jLabel61))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlBaN1Layout.setVerticalGroup(
            pnlBaN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaN1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblBaN_pic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBaN_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel61)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlBaN2.setBackground(new java.awt.Color(255, 153, 51));
        pnlBaN2.setPreferredSize(new java.awt.Dimension(244, 288));

        lblBaN2_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot_2023-09-05_164911_179x180m2.png"))); // NOI18N
        lblBaN2_pic.setName("Screenshot_2023-09-05_164911_179x180m2.png"); // NOI18N
        lblBaN2_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBaN2_picMouseClicked(evt);
            }
        });

        lblBaN2_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBaN2_name.setText("Stanley Fiberglass Tape Measure");

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel63.setText("R499.99");

        javax.swing.GroupLayout pnlBaN2Layout = new javax.swing.GroupLayout(pnlBaN2);
        pnlBaN2.setLayout(pnlBaN2Layout);
        pnlBaN2Layout.setHorizontalGroup(
            pnlBaN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaN2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(pnlBaN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBaN2_pic)
                    .addComponent(lblBaN2_name, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        pnlBaN2Layout.setVerticalGroup(
            pnlBaN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaN2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblBaN2_pic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBaN2_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel63)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlBaN3.setBackground(new java.awt.Color(255, 153, 51));
        pnlBaN3.setPreferredSize(new java.awt.Dimension(244, 288));

        lblBaN3_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot_2023-09-05_164920_179x180m3.png"))); // NOI18N
        lblBaN3_pic.setName("Screenshot_2023-09-05_164920_179x180m3.png"); // NOI18N
        lblBaN3_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBaN3_picMouseClicked(evt);
            }
        });

        lblBaN3_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBaN3_name.setText("Ross Builders Square");

        jLabel65.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel65.setText("R160.00");

        javax.swing.GroupLayout pnlBaN3Layout = new javax.swing.GroupLayout(pnlBaN3);
        pnlBaN3.setLayout(pnlBaN3Layout);
        pnlBaN3Layout.setHorizontalGroup(
            pnlBaN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaN3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(pnlBaN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBaN3_pic)
                    .addComponent(lblBaN3_name)
                    .addComponent(jLabel65))
                .addGap(20, 20, 20))
        );
        pnlBaN3Layout.setVerticalGroup(
            pnlBaN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaN3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblBaN3_pic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBaN3_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel65)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlPliers1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlBaN1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pnlDrill1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pnlScrewDriver1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pnlSpanner1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlHammer1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(pnlBaN2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnlBaN3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(pnlPliers2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnlPliers3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(pnlSpanner2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addComponent(pnlSpanner3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pnlDrill2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(pnlScrewDriver2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlScrewDriver3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlDrill3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pnlHammer2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(pnlHammer3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHammer2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlHammer1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlHammer3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlDrill1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(pnlDrill2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlScrewDriver1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlScrewDriver3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlScrewDriver2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlSpanner2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlSpanner1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pnlPliers2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pnlPliers3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(68, 68, 68))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(pnlPliers1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlBaN2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlBaN1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlBaN3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(pnlSpanner3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pnlDrill3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 130, 860, 400);

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2023-09-05 174938.png"))); // NOI18N
        getContentPane().add(jLabel67);
        jLabel67.setBounds(-160, 90, 1020, 100);

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ContactDetails.png"))); // NOI18N
        getContentPane().add(jLabel69);
        jLabel69.setBounds(30, 510, 780, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2023-09-05 131333.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-10, 530, 980, 54);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // creates login frame and focus it
        LoginForm lf= new LoginForm();
        lf.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void pnlHammer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHammer1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_pnlHammer1MouseClicked

    private void btnCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartActionPerformed
        // Creates the cart frame and focuses it
        if (btnLogin.isVisible()){
           Cart c =new Cart();
           c.setVisible(true);
           setVisible(false); 
        }else{
           String user =lblUser.getText();
           Cart c =new Cart(user);
           c.setVisible(true);
           setVisible(false);
        }
    }//GEN-LAST:event_btnCartActionPerformed
    //Extention to everything below. Checks if the user has logged in
    public String CheckbtnLogin(){
        if (btnLogin.isVisible()) {
            return null;
        } else {
            return lblUser.getText();
        }
    }
    // Extention of the everything below. recusive call to create the frame
    public void createDescription(String itemName, String nameURL){
        HammerDescription hd =new HammerDescription(CheckbtnLogin(),nameURL,itemName);
        hd.setVisible(true);
        setVisible(false);    
    }
    
    //Everything private below creates the next description frame and sends the name and iconURL of the selected tool to be displayed to the new frame class.
    private void lblHammer1_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHammer1_picMouseClicked
        // TODO add your handling code here:
        String itemName = lblHammer1_name.getText();
        String nameURL = lblHammer1_pic.getName();
        setName(nameURL);
        createDescription(itemName, nameURL);
          
    }//GEN-LAST:event_lblHammer1_picMouseClicked

    private void lblHammer2_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHammer2_picMouseClicked
        // TODO add your handling code here:
        String itemName = lblHammer2_name.getText();
        String nameURL = lblHammer2_pic.getName();
        setName(nameURL);
        createDescription(itemName, nameURL);
    }//GEN-LAST:event_lblHammer2_picMouseClicked

    private void lblHammer3_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHammer3_picMouseClicked
        // TODO add your handling code here:
        String itemName = lblHammer3_name.getText();
        String nameURL = lblHammer3_pic.getName();
        setName(nameURL);
        createDescription(itemName, nameURL);
    }//GEN-LAST:event_lblHammer3_picMouseClicked

    private void lblDrill1_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDrill1_picMouseClicked
        // TODO add your handling code here:
        String itemName = lblDrill1_name.getText();
        String nameURL = lblDrill1_pic.getName();
        setName(nameURL);
        createDescription(itemName, nameURL);
    }//GEN-LAST:event_lblDrill1_picMouseClicked

    private void lblDrill3_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDrill3_picMouseClicked
        // TODO add your handling code here:
        String itemName = lblDrill3_name.getText();
        String nameURL = lblDrill3_pic.getName();
        setName(nameURL);
        createDescription(itemName, nameURL);
    }//GEN-LAST:event_lblDrill3_picMouseClicked

    private void lblDrill2_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDrill2_picMouseClicked
        // TODO add your handling code here:
        String itemName = lblDrill2_name.getText();
        String nameURL = lblDrill2_pic.getName();
        setName(nameURL);
        createDescription(itemName, nameURL);
    }//GEN-LAST:event_lblDrill2_picMouseClicked

    private void lblScrew1_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblScrew1_picMouseClicked
        // TODO add your handling code here:
        String itemName = lblScrew1_name.getText();
        String nameURL = lblScrew1_pic.getName();
        setName(nameURL);
        createDescription(itemName, nameURL);
    }//GEN-LAST:event_lblScrew1_picMouseClicked

    private void lblScrew2_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblScrew2_picMouseClicked
        // TODO add your handling code here:
        String itemName = lblScrew2_name.getText();
        String nameURL = lblScrew2_pic.getName();
        setName(nameURL);
        createDescription(itemName, nameURL);
    }//GEN-LAST:event_lblScrew2_picMouseClicked

    private void lblScrew3_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblScrew3_picMouseClicked
        // TODO add your handling code here:
        String itemName = lblScrew3_name.getText();
        String nameURL = lblScrew3_pic.getName();
        setName(nameURL);
        createDescription(itemName, nameURL);
    }//GEN-LAST:event_lblScrew3_picMouseClicked

    private void lblSpanner1_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpanner1_picMouseClicked
        // TODO add your handling code here:
        String itemName = lblSpanner1_name.getText();
        String nameURL = lblSpanner1_pic.getName();
        setName(nameURL);
        createDescription(itemName, nameURL);
    }//GEN-LAST:event_lblSpanner1_picMouseClicked

    private void lblSpanner2_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpanner2_picMouseClicked
        // TODO add your handling code here:
        String itemName = lblSpanner2_name.getText();
        String nameURL = lblSpanner2_pic.getName();
        setName(nameURL);
        createDescription(itemName, nameURL);
    }//GEN-LAST:event_lblSpanner2_picMouseClicked

    private void lblSpanner3_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpanner3_picMouseClicked
        // TODO add your handling code here:
        String itemName = lblSpanner3_name.getText();
        String nameURL = lblSpanner3_pic.getName();
        setName(nameURL);
        createDescription(itemName, nameURL);
    }//GEN-LAST:event_lblSpanner3_picMouseClicked

    private void lblPliers1_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPliers1_picMouseClicked
        // TODO add your handling code here:
        String itemName = lblPliers1_name.getText();
        String nameURL = lblPliers1_pic.getName();
        setName(nameURL);
        createDescription(itemName, nameURL);
    }//GEN-LAST:event_lblPliers1_picMouseClicked

    private void lblPliers2_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPliers2_picMouseClicked
        // TODO add your handling code here:
        String itemName = lblPliers2_name.getText();
        String nameURL = lblPliers2_pic.getName();
        setName(nameURL);
        createDescription(itemName, nameURL);
    }//GEN-LAST:event_lblPliers2_picMouseClicked

    private void lblPliers3_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPliers3_picMouseClicked
        // TODO add your handling code here:
        String itemName = lblPliers3_name.getText();
        String nameURL = lblPliers3_pic.getName();
        setName(nameURL);
        createDescription(itemName, nameURL);
    }//GEN-LAST:event_lblPliers3_picMouseClicked

    private void lblBaN_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBaN_picMouseClicked
        // TODO add your handling code here:
        String itemName = lblBaN_name.getText();
        String nameURL = lblBaN_pic.getName();
        setName(nameURL);
        createDescription(itemName, nameURL);
    }//GEN-LAST:event_lblBaN_picMouseClicked

    private void lblBaN2_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBaN2_picMouseClicked
        // TODO add your handling code here:
        String itemName = lblBaN2_name.getText();
        String nameURL = lblBaN2_pic.getName();
        setName(nameURL);
        createDescription(itemName, nameURL);
    }//GEN-LAST:event_lblBaN2_picMouseClicked

    private void lblBaN3_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBaN3_picMouseClicked
        // TODO add your handling code here:
        String itemName = lblBaN3_name.getText();
        String nameURL = lblBaN3_pic.getName();
        setName(nameURL);
        createDescription(itemName, nameURL);
    }//GEN-LAST:event_lblBaN3_picMouseClicked
    
    
    private String name = "";
    public String getName(){
        return name;
    }
    public void setName(String newName){
        this.name = newName;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCart;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnProfile;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBaN2_name;
    private javax.swing.JLabel lblBaN2_pic;
    private javax.swing.JLabel lblBaN3_name;
    private javax.swing.JLabel lblBaN3_pic;
    private javax.swing.JLabel lblBaN_name;
    private javax.swing.JLabel lblBaN_pic;
    private javax.swing.JLabel lblDrill1_name;
    private javax.swing.JLabel lblDrill1_pic;
    private javax.swing.JLabel lblDrill1_price;
    private javax.swing.JLabel lblDrill2_name;
    private javax.swing.JLabel lblDrill2_pic;
    private javax.swing.JLabel lblDrill2_price;
    private javax.swing.JLabel lblDrill3_name;
    private javax.swing.JLabel lblDrill3_pic;
    private javax.swing.JLabel lblDrill3_price;
    private javax.swing.JLabel lblHammer1_name;
    private javax.swing.JLabel lblHammer1_pic;
    private javax.swing.JLabel lblHammer1_price;
    private javax.swing.JLabel lblHammer2_name;
    private javax.swing.JLabel lblHammer2_pic;
    private javax.swing.JLabel lblHammer2_price;
    private javax.swing.JLabel lblHammer3_name;
    private javax.swing.JLabel lblHammer3_pic;
    private javax.swing.JLabel lblHammer3_price;
    private javax.swing.JLabel lblPliers1_name;
    private javax.swing.JLabel lblPliers1_pic;
    private javax.swing.JLabel lblPliers1_price;
    private javax.swing.JLabel lblPliers2_name;
    private javax.swing.JLabel lblPliers2_pic;
    private javax.swing.JLabel lblPliers2_price;
    private javax.swing.JLabel lblPliers3_name;
    private javax.swing.JLabel lblPliers3_pic;
    private javax.swing.JLabel lblPliers3_price;
    private javax.swing.JLabel lblScrew1_name;
    private javax.swing.JLabel lblScrew1_pic;
    private javax.swing.JLabel lblScrew1_price;
    private javax.swing.JLabel lblScrew2_name;
    private javax.swing.JLabel lblScrew2_pic;
    private javax.swing.JLabel lblScrew2_price;
    private javax.swing.JLabel lblScrew3_name;
    private javax.swing.JLabel lblScrew3_pic;
    private javax.swing.JLabel lblScrew3_price;
    private javax.swing.JLabel lblSpanner1_name;
    private javax.swing.JLabel lblSpanner1_pic;
    private javax.swing.JLabel lblSpanner1_price;
    private javax.swing.JLabel lblSpanner2_name;
    private javax.swing.JLabel lblSpanner2_pic;
    private javax.swing.JLabel lblSpanner2_price;
    private javax.swing.JLabel lblSpanner3_name;
    private javax.swing.JLabel lblSpanner3_pic;
    private javax.swing.JLabel lblSpanner3_price;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlBaN1;
    private javax.swing.JPanel pnlBaN2;
    private javax.swing.JPanel pnlBaN3;
    private javax.swing.JPanel pnlDrill1;
    private javax.swing.JPanel pnlDrill2;
    private javax.swing.JPanel pnlDrill3;
    private javax.swing.JPanel pnlHammer1;
    private javax.swing.JPanel pnlHammer2;
    private javax.swing.JPanel pnlHammer3;
    private javax.swing.JPanel pnlPliers1;
    private javax.swing.JPanel pnlPliers2;
    private javax.swing.JPanel pnlPliers3;
    private javax.swing.JPanel pnlScrewDriver1;
    private javax.swing.JPanel pnlScrewDriver2;
    private javax.swing.JPanel pnlScrewDriver3;
    private javax.swing.JPanel pnlSpanner1;
    private javax.swing.JPanel pnlSpanner2;
    private javax.swing.JPanel pnlSpanner3;
    // End of variables declaration//GEN-END:variables
}
